# HW 3

### Question 1

In [1]:
from scripts.factor import prime_factors
# a 
print(prime_factors(129))
print(190//2)
print(191 % 3)
print(prime_factors(43))
print((190/2)*(42/2))
print(191%43)
print(prime_factors(19))

[(3, 1), (43, 1)]
95
2
[(43, 1)]
1995.0
19
[(19, 1)]


In [2]:
# b
from scripts.factor import prime_factors
print(prime_factors(795))
print(1530//2)
print(1530/2*(52/2))

[(3, 1), (5, 1), (53, 1)]
765
19890.0


### Question 2

In [3]:
# a
print(prime_factors(79))
print(20*39)
print(79%41)
print(prime_factors(38))
print((41**2-1)/8)

[(79, 1)]
780
38
[(2, 1), (19, 1)]
210.0


In [4]:
# b 
print(prime_factors(100))
print((-1)**((547**2-1)/8))
print(547%5)
print(prime_factors(547))

[(2, 2), (5, 2)]
-1.0
2
[(547, 1)]


In [5]:
# c
print(prime_factors(461))
print(230*209)
print(461 % 419)
print(prime_factors(42))
print((419**2-1)/8)
print(prime_factors(419))
print(419 % 3)
print((418/2)*(6/2))
print(419%7)
print(48//8)

[(461, 1)]
48070
42
[(2, 1), (3, 1), (7, 1)]
21945.0
[(419, 1)]
2
627.0
6
6


### Question 3

##### Step 1 - Setting up
$n = p*q$

$x\equiv s^2\:mod\:n$

$y=u^2\:mod\:n$

##### Step 2 - Bob chooses b=0 or b=1
##### Step 3 - Alice responds accordingly
if b==0:
    $z=u$
    
else:
    $z=s*u$
##### Step 4 - Bob verifies
if b==0:
    $z^2\equiv y\:mod\:n$
    
else:
    $z^2\equiv x*y\:mod\:n$

#### a.)

In [20]:
n = 58014043
x = 18059241
x_inv = pow(x, -1, n)

b_vals = [0,1,1,0]
u_vals = [15,2,3,30]
z_vals = [u_vals[0], 3245, 78956, u_vals[3]]
y_vals = [u_vals[0]**2, pow(z_vals[1],2,n)*x_inv % n,pow(z_vals[2],2,n)*x_inv % n,u_vals[3]**2]

print("trial: (b,u,y,z)")
trials = list(zip(b_vals, u_vals, y_vals, z_vals))

trial: (b,u,y,z)


In [21]:
for i, (b, u, y, z) in enumerate(trials):
    print(f'Trial {i}: b={b:3}, u={u:3}, y={y:3}, z={z:3}')
print()
trial_num = 0
for b, u, y, z in trials:
    if b==0:
        print(f"Trial {trial_num}: b is 0, Bob responds: ", pow(z,2, n) == (y % n))
    else:
        print(f"Trial {trial_num}: b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))
    trial_num += 1

Trial 0: b=  0, u= 15, y=225, z= 15
Trial 1: b=  1, u=  2, y=57235916, z=3245
Trial 2: b=  1, u=  3, y=14316805, z=78956
Trial 3: b=  0, u= 30, y=900, z= 30

Trial 0: b is 0, Bob responds:  True
Trial 1: b is 1, Bob responds:  True
Trial 2: b is 1, Bob responds:  True
Trial 3: b is 0, Bob responds:  True


#### b.)

In [8]:
n = 58014043
x = 8952064
s = -1
for i in range(n):
    if pow(i, 2, n) == x:
        s = i
        break;

In [9]:
s

2992

In [10]:
n = 58014043
x = 8952064
b_vals = [1,1,0,0]
u_vals = [45,42,7,100]
y_vals = [u**2 for u in u_vals]
z_vals = [u_vals[i] if b==0 else s*u_vals[i] for i, b in enumerate(b_vals)]

print("trial: (b,u,y,z)")
trials = list(zip(b_vals, u_vals, y_vals, z_vals))

trial: (b,u,y,z)


In [11]:
for i, (b, u, y, z) in enumerate(trials):
    print(f'Trial {i}: b={b:3}, u={u:3}, y={y:3}, z={z:3}')
print()
trial_num = 0
for b, u, y, z in trials:
    if b==0:
        print(f"Trial {trial_num}: b is 0, Bob responds: ", pow(z,2, n) == (y % n))
    else:
        print(f"Trial {trial_num}: b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))
    trial_num += 1

Trial 0: b=  1, u= 45, y=2025, z=134640
Trial 1: b=  1, u= 42, y=1764, z=125664
Trial 2: b=  0, u=  7, y= 49, z=  7
Trial 3: b=  0, u=100, y=10000, z=100

Trial 0: b is 1, Bob responds:  True
Trial 1: b is 1, Bob responds:  True
Trial 2: b is 0, Bob responds:  True
Trial 3: b is 0, Bob responds:  True


#### Problem 4

In [12]:
import numpy as np

p = 3
q = 7
n = p*q
table = np.ones(shape=(p,q))
for i in range(n):
    table[i%p][i%q] = i 
print(table)

[[ 0. 15.  9.  3. 18. 12.  6.]
 [ 7.  1. 16. 10.  4. 19. 13.]
 [14.  8.  2. 17. 11.  5. 20.]]


In [13]:
a = 15
print(15%3)
print()

0



In [25]:
# pseudo- code found at https://primes.utm.edu/glossary/page.php?sort=JacobiSymbol
def jacobi(a, n):
    j = 1
    while a != 0:
        while a % 2 == 0:
            a = a/2
            check = n % 8
            if check == 3 or check == 5:
                j = -j
        a, n = n, a
        check = a % 4
        if check == 3 and (n % 4) == 3:
            j == -j
        a = a % n
    if n == 1:
        return j
    return 0

In [15]:
jac_table = np.ones(table.shape)
for i in range(table.shape[0]):
    for j in range(table.shape[1]):
        jac_table[i][j] = jacobi(table[i][j], n)

In [16]:
jac_table

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1., -1.,  1., -1., -1.],
       [ 0., -1., -1.,  1., -1.,  1.,  1.]])

In [17]:
def print_squares(p):
    l = []
    for i in range(0, p):
        square = pow(i, 2, p)
        pos_item = (i, square)
        l.append(pos_item)
    squares = set([item[1] for item in l])
    print(f'squares mod {p}: {squares}\n')
    
    square_roots = dict(zip(squares, []*len(squares)))
    for num, square in l:
        if not square_roots.get(square):
            square_roots[square] = []
        square_roots[square].append(num)

    print('dict mapping squares --> list of square roots')
    for square, roots in square_roots.items():
        print(f'{square:2}: {roots}')

In [22]:
print_squares(7)
print_squares(3)
print_squares(21)

squares mod 7: {0, 1, 2, 4}

dict mapping squares --> list of square roots
 0: [0]
 1: [1, 6]
 4: [2, 5]
 2: [3, 4]
squares mod 3: {0, 1}

dict mapping squares --> list of square roots
 0: [0]
 1: [1, 2]
squares mod 21: {0, 1, 4, 7, 9, 15, 16, 18}

dict mapping squares --> list of square roots
 0: [0]
 1: [1, 8, 13, 20]
 4: [2, 5, 16, 19]
 9: [3, 18]
16: [4, 10, 11, 17]
15: [6, 15]
 7: [7, 14]
18: [9, 12]
