# Zero Knowledge Proofs

$n = p*q$

In [6]:
n = 1549411

$x=s^2\:mod\:n$

In [7]:
x = 1075922

$y=u^2\:mod\:n$

In [8]:
y=1361157

## Step 2 - Bob responds with {0,1}

In [9]:
b=0

## Step 3 - Alice responds accordingly
if b==0:
    $z=u$
    
else:
    $z=s*u$

In [10]:
z = 4467

## Step 4 - Bob verifies
if b==0:
    $z^2\equiv y\:mod\:n$
    
else:
    $z^2\equiv x*y\:mod\:n$

In [11]:
if b==0:
    print("b is 0, Bob responds: ",pow(z,2, n) == (y % n))
else:
    print("b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))

b is 0, Bob responds:  True


# Trials

In [2]:
n = 1549411
x = 1075922

In [4]:
# Trial 0

y = x**2 % n
b = 0
z = 4467
if b==0:
    print("b is 0, Bob responds: ",pow(z,2, n) == (y % n))
else:
    print("b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))

b is 0, Bob responds:  False


In [5]:
# Trial 1

y = 1361157
b = 0
z = 4467
if b==0:
    print("b is 0, Bob responds: ",pow(z,2, n) == (y % n))
else:
    print("b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))

b is 0, Bob responds:  True


In [6]:
# Trial 2
y = 743044
b = 1
z = 257646
if b==0:
    print("b is 0, Bob responds: ",pow(z,2, n) == (y % n))
else:
    print("b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))

b is 1, Bob responds:  True


In [10]:
# Trial 3
y = 1485354
b = 1
z = 811105
if b==0:
    print("b is 0, Bob responds: ",pow(z,2, n) == (y % n))
else:
    print("b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))

b is 1, Bob responds:  True


In [11]:
# Trial 4
y = 752906
b = 0
z = 66399
if b==0:
    print("b is 0, Bob responds: ",pow(z,2, n) == (y % n))
else:
    print("b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))

b is 0, Bob responds:  True


In [12]:
# Trial 5
y = 1394003
b = 0
z = 88324
if b==0:
    print("b is 0, Bob responds: ",pow(z,2, n) == (y % n))
else:
    print("b is 1, Bob responds: ", pow(z,2, n) == (x*y % n))

b is 0, Bob responds:  False


# Chinese Remainder Theorem

In [6]:
# header = [f'{i:5}' for i in range(7)]

# for num in header:
#     print(num, end=' ')
# print()
# print("-"*45)
# for i in range(5):
#     print(f'{i}|', end = '')
#     for j in range(7):
#         print(f'{(i % 5) * (j % 7):5}', end=' ')
#     print()
import numpy as np
table = [[0 for i in range(7)] for j in range(5)]
table = np.ones(shape=(5,7))
for i in range(35):
    table[i%5][i%7] = i 
print(table)

[[ 0. 15. 30. 10. 25.  5. 20.]
 [21.  1. 16. 31. 11. 26.  6.]
 [ 7. 22.  2. 17. 32. 12. 27.]
 [28.  8. 23.  3. 18. 33. 13.]
 [14. 29.  9. 24.  4. 19. 34.]]


In [11]:
for i in range(1, 6):
    print(f'i: {i} -> {13*i + 6}')

i: 1 -> 19
i: 2 -> 32
i: 3 -> 45
i: 4 -> 58
i: 5 -> 71


$$48 \equiv x^2\:mod\:143 \\143= 11*13$$